jobs:
  - name: production-specific-queries-full-snapshots
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-prod
          - get: aws-internal-compute
            trigger: false
          - get: aws-ingestion
            trigger: false
          - get: dataworks-behavioural-framework
            trigger: false
          - get: aws-snapshot-sender
            trigger: false
          - get: dataworks-behavioural-framework-manifest-comparison
            trigger: false
      - in_parallel:
          - .: (( inject meta.plan.terraform-output-ingest ))
            params:
              TF_WORKSPACE: production
          - .: (( inject meta-manifest-comparison.plan.terraform-output-internal-compute ))
            params:
              TF_WORKSPACE: production
          - .: (( inject meta-manifest-comparison.plan.terraform-output-snapshot-sender ))
            params:
              TF_WORKSPACE: production
      - .: (( inject meta-manifest-comparison.plan.generate-manifest-comparison ))
        task: run-specific-queries-full-snapshots
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            MANIFEST_COMPARISON_VERIFY_RESULTS: "false"
            MANIFEST_COMPARISON_MARGIN_OF_ERROR_MINUTES: "15"
            MANIFEST_COMPARISON_SNAPSHOT_TYPE: "full"
            E2E_FEATURE_TAG_FILTER: "@manifest-comparison-specific"
