jobs:
  - name: management
    max_in_flight: 1
    plan:
      - get: dataworks-behavioural-framework
        trigger: true
        passed:
          - management-dev
      - .: (( inject meta-dataworks-behavioural-framework.plan.terraform-bootstrap ))
      - .: (( inject meta-dataworks-behavioural-framework.plan.terraform-apply ))
        params:
          TF_WORKSPACE: "management"
      - .: (( inject meta-dataworks-behavioural-framework.plan.terraform-plan ))
        params:
          TF_WORKSPACE: "management"
