jobs:
  - name: qa-run-with-image
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-qa
          - get: ecr-dwpdigital-dataworks-behavioural-framework
            trigger: true
          - get: dataworks-behavioural-framework
            trigger: false]
]
      - .: (( inject meta-dataworks-behavioural-framework.plan.dataworks-e2e-tests-run-with-image ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            E2E_TEST_TIMEOUT: 600
            E2E_FEATURE_TAG_FILTER: "@end-to-end"
    ensure:
      do:
        - .: (( inject meta-dataworks-behavioural-framework.plan.tear-down ))
          config:
            params:
              AWS_ACC: ((aws_account.qa))
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
