jobs:
  - name: qa
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-qa
          - get: dataworks-behavioural-framework
            trigger: true
          - get: aws-ingestion
            trigger: false

      - .: (( inject meta.plan.terraform-output-ingest ))
        config:
          params:
            TF_WORKSPACE: qa
      - .: (( inject meta-dataworks-behavioural-framework.plan.upload-fixture-data ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
      - .: (( inject meta-dataworks-behavioural-framework.plan.phase-one-e2e-tests ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            E2E_TEST_TIMEOUT: 600
            E2E_FEATURE_TAG_FILTER: "@end-to-end"
    ensure:
      do:
        - .: (( inject meta-dataworks-behavioural-framework.plan.tear-down ))
          config:
            params:
              AWS_ACC: ((aws_account.qa))
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
