jobs:
  - name: dev-load-test-kafka
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-development
          - get: dataworks-behavioural-framework
            trigger: false
      - .: (( inject meta-load-test.plan.load-tests ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            NUMBER_OF_TOPICS_TO_USE: 10
            LOAD_TESTS_KAFKA_MESSAGE_VOLUME: 100
            LOAD_TESTS_KAFKA_RECORD_COUNT: 100
            LOAD_TESTS_KAFKA_RANDOM_KEY: "true"
            LOAD_TEST_TYPE: "kafka"
            ENVIRONMENT_JOB_NAME: "dev-load-test"
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
