jobs:
  - name: integration-load-test-import
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-integration
          - get: dataworks-behavioural-framework
            trigger: false
      - .: (( inject meta-load-test.plan.load-tests ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            NUMBER_OF_TOPICS_TO_USE: 100
            LOAD_TEST_TYPE: import
            LOAD_TEST_KEY_METHOD: "different"
            ENVIRONMENT_JOB_NAME: "integration-load-test"
